# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MissionModule.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MissionModule.proto',
  package='MissionModule',
  syntax='proto3',
  serialized_options=b'Z!../internal/pkg/ba_proto;ba_proto\252\002\030Google.Protobuf.ba_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13MissionModule.proto\x12\rMissionModule\"\xd5\x02\n\x0e\x41utonomyStatus\x12:\n\ttelemetry\x18\x01 \x01(\x0b\x32\'.MissionModule.AutonomyStatus.Telemetry\x12\x32\n\x05state\x18\x02 \x01(\x0e\x32#.MissionModule.AutonomyStatus.State\x12-\n\x08nextStop\x18\x03 \x01(\x0b\x32\x16.MissionModule.StationH\x00\x88\x01\x01\x1aS\n\tTelemetry\x12\r\n\x05speed\x18\x01 \x01(\x01\x12\x0c\n\x04\x66uel\x18\x02 \x01(\x01\x12)\n\x08position\x18\x03 \x01(\x0b\x32\x17.MissionModule.Position\"B\n\x05State\x12\x08\n\x04IDLE\x10\x00\x12\t\n\x05\x44RIVE\x10\x01\x12\x0b\n\x07IN_STOP\x10\x02\x12\x0c\n\x08OBSTACLE\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x42\x0b\n\t_nextStop\"\xac\x01\n\x0f\x41utonomyCommand\x12%\n\x05stops\x18\x01 \x03(\x0b\x32\x16.MissionModule.Station\x12\r\n\x05route\x18\x02 \x01(\t\x12\x35\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32%.MissionModule.AutonomyCommand.Action\",\n\x06\x41\x63tion\x12\r\n\tNO_ACTION\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\t\n\x05START\x10\x02\">\n\rAutonomyError\x12-\n\rfinishedStops\x18\x01 \x03(\x0b\x32\x16.MissionModule.Station\"B\n\x07Station\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x08position\x18\x02 \x01(\x0b\x32\x17.MissionModule.Position\"A\n\x08Position\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x42>Z!../internal/pkg/ba_proto;ba_proto\xaa\x02\x18Google.Protobuf.ba_protob\x06proto3'
)



_AUTONOMYSTATUS_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='MissionModule.AutonomyStatus.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DRIVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IN_STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OBSTACLE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=301,
  serialized_end=367,
)
_sym_db.RegisterEnumDescriptor(_AUTONOMYSTATUS_STATE)

_AUTONOMYCOMMAND_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='MissionModule.AutonomyCommand.Action',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ACTION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=511,
  serialized_end=555,
)
_sym_db.RegisterEnumDescriptor(_AUTONOMYCOMMAND_ACTION)


_AUTONOMYSTATUS_TELEMETRY = _descriptor.Descriptor(
  name='Telemetry',
  full_name='MissionModule.AutonomyStatus.Telemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='MissionModule.AutonomyStatus.Telemetry.speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fuel', full_name='MissionModule.AutonomyStatus.Telemetry.fuel', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='MissionModule.AutonomyStatus.Telemetry.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=299,
)

_AUTONOMYSTATUS = _descriptor.Descriptor(
  name='AutonomyStatus',
  full_name='MissionModule.AutonomyStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='telemetry', full_name='MissionModule.AutonomyStatus.telemetry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='MissionModule.AutonomyStatus.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nextStop', full_name='MissionModule.AutonomyStatus.nextStop', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_AUTONOMYSTATUS_TELEMETRY, ],
  enum_types=[
    _AUTONOMYSTATUS_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_nextStop', full_name='MissionModule.AutonomyStatus._nextStop',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=39,
  serialized_end=380,
)


_AUTONOMYCOMMAND = _descriptor.Descriptor(
  name='AutonomyCommand',
  full_name='MissionModule.AutonomyCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stops', full_name='MissionModule.AutonomyCommand.stops', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route', full_name='MissionModule.AutonomyCommand.route', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='MissionModule.AutonomyCommand.action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUTONOMYCOMMAND_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=555,
)


_AUTONOMYERROR = _descriptor.Descriptor(
  name='AutonomyError',
  full_name='MissionModule.AutonomyError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='finishedStops', full_name='MissionModule.AutonomyError.finishedStops', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=619,
)


_STATION = _descriptor.Descriptor(
  name='Station',
  full_name='MissionModule.Station',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MissionModule.Station.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='MissionModule.Station.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=687,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='MissionModule.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='MissionModule.Position.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='MissionModule.Position.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='MissionModule.Position.altitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=754,
)

_AUTONOMYSTATUS_TELEMETRY.fields_by_name['position'].message_type = _POSITION
_AUTONOMYSTATUS_TELEMETRY.containing_type = _AUTONOMYSTATUS
_AUTONOMYSTATUS.fields_by_name['telemetry'].message_type = _AUTONOMYSTATUS_TELEMETRY
_AUTONOMYSTATUS.fields_by_name['state'].enum_type = _AUTONOMYSTATUS_STATE
_AUTONOMYSTATUS.fields_by_name['nextStop'].message_type = _STATION
_AUTONOMYSTATUS_STATE.containing_type = _AUTONOMYSTATUS
_AUTONOMYSTATUS.oneofs_by_name['_nextStop'].fields.append(
  _AUTONOMYSTATUS.fields_by_name['nextStop'])
_AUTONOMYSTATUS.fields_by_name['nextStop'].containing_oneof = _AUTONOMYSTATUS.oneofs_by_name['_nextStop']
_AUTONOMYCOMMAND.fields_by_name['stops'].message_type = _STATION
_AUTONOMYCOMMAND.fields_by_name['action'].enum_type = _AUTONOMYCOMMAND_ACTION
_AUTONOMYCOMMAND_ACTION.containing_type = _AUTONOMYCOMMAND
_AUTONOMYERROR.fields_by_name['finishedStops'].message_type = _STATION
_STATION.fields_by_name['position'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['AutonomyStatus'] = _AUTONOMYSTATUS
DESCRIPTOR.message_types_by_name['AutonomyCommand'] = _AUTONOMYCOMMAND
DESCRIPTOR.message_types_by_name['AutonomyError'] = _AUTONOMYERROR
DESCRIPTOR.message_types_by_name['Station'] = _STATION
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutonomyStatus = _reflection.GeneratedProtocolMessageType('AutonomyStatus', (_message.Message,), {

  'Telemetry' : _reflection.GeneratedProtocolMessageType('Telemetry', (_message.Message,), {
    'DESCRIPTOR' : _AUTONOMYSTATUS_TELEMETRY,
    '__module__' : 'MissionModule_pb2'
    # @@protoc_insertion_point(class_scope:MissionModule.AutonomyStatus.Telemetry)
    })
  ,
  'DESCRIPTOR' : _AUTONOMYSTATUS,
  '__module__' : 'MissionModule_pb2'
  # @@protoc_insertion_point(class_scope:MissionModule.AutonomyStatus)
  })
_sym_db.RegisterMessage(AutonomyStatus)
_sym_db.RegisterMessage(AutonomyStatus.Telemetry)

AutonomyCommand = _reflection.GeneratedProtocolMessageType('AutonomyCommand', (_message.Message,), {
  'DESCRIPTOR' : _AUTONOMYCOMMAND,
  '__module__' : 'MissionModule_pb2'
  # @@protoc_insertion_point(class_scope:MissionModule.AutonomyCommand)
  })
_sym_db.RegisterMessage(AutonomyCommand)

AutonomyError = _reflection.GeneratedProtocolMessageType('AutonomyError', (_message.Message,), {
  'DESCRIPTOR' : _AUTONOMYERROR,
  '__module__' : 'MissionModule_pb2'
  # @@protoc_insertion_point(class_scope:MissionModule.AutonomyError)
  })
_sym_db.RegisterMessage(AutonomyError)

Station = _reflection.GeneratedProtocolMessageType('Station', (_message.Message,), {
  'DESCRIPTOR' : _STATION,
  '__module__' : 'MissionModule_pb2'
  # @@protoc_insertion_point(class_scope:MissionModule.Station)
  })
_sym_db.RegisterMessage(Station)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'MissionModule_pb2'
  # @@protoc_insertion_point(class_scope:MissionModule.Position)
  })
_sym_db.RegisterMessage(Position)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
