@startuml command_activity_diagram
<style>
    activityDiagram {
        BackgroundColor #88bcff
        FontSize 12
    }
    start {BackgroundColor black}
    stop {BackgroundColor black}
    document {
        BackgroundColor white
    }
    note {
        BackgroundColor #ffee55
    }
</style>
start

note right
    Device accepts
    command with action
    and list of stops.
end note

note left
    Autonomy stores the `nextStop` -
    - name of the next stop
    it drives to, or empty string if
    it is not driving.
end note

switch (Action value)
case (\n   STOP)
    #LightGray:Set nextStop to "";
    note left
        This branch is
        always used to
        stop the car.
    end note
    #LightGray:Autonomy cancels driving;
    #Pink:send status with IDLE state;
case (\n  NO_ACTION)
    #LightGray::Set nextStop to "";
    note right
        The stops as a
        consequence of
        not having another
        stop to drive to.
    end note
    #LightGray:Autonomy cancels driving;
    #Pink:send status with IDLE state;
case (\n   START)
    if (Is list of stops empty?) then (No)
        if (Is nextStop equal to name of stops[0]?) then (No)
            #LightGray::Set nextStop to first
            stop in the stop list;
            #LightGray:Autonomy cancels driving;
            #LightGray:Start driving to nextStop;
            #Pink:send status with DRIVE state;
        else (Yes)
        endif
    else (Yes)
        #LightGray:Set nextStop to "";
        #LightGray:Autonomy cancels driving;
        #Pink:send status with IDLE state;
    endif
endswitch
stop

@enduml