// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MissionModule.proto
// Protobuf C++ Version: 5.27.2

#include "MissionModule.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace MissionModule {

inline constexpr Position::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : latitude_{0},
        longitude_{0},
        altitude_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Position::Position(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PositionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PositionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PositionDefaultTypeInternal() {}
  union {
    Position _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PositionDefaultTypeInternal _Position_default_instance_;

inline constexpr Station::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        position_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Station::Station(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StationDefaultTypeInternal() {}
  union {
    Station _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StationDefaultTypeInternal _Station_default_instance_;

inline constexpr AutonomyStatus_Telemetry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{nullptr},
        speed_{0},
        fuel_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AutonomyStatus_Telemetry::AutonomyStatus_Telemetry(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AutonomyStatus_TelemetryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AutonomyStatus_TelemetryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AutonomyStatus_TelemetryDefaultTypeInternal() {}
  union {
    AutonomyStatus_Telemetry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AutonomyStatus_TelemetryDefaultTypeInternal _AutonomyStatus_Telemetry_default_instance_;

inline constexpr AutonomyStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        telemetry_{nullptr},
        nextstop_{nullptr},
        state_{static_cast< ::MissionModule::AutonomyStatus_State >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR AutonomyStatus::AutonomyStatus(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AutonomyStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AutonomyStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AutonomyStatusDefaultTypeInternal() {}
  union {
    AutonomyStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AutonomyStatusDefaultTypeInternal _AutonomyStatus_default_instance_;

inline constexpr AutonomyError::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : finishedstops_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AutonomyError::AutonomyError(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AutonomyErrorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AutonomyErrorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AutonomyErrorDefaultTypeInternal() {}
  union {
    AutonomyError _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AutonomyErrorDefaultTypeInternal _AutonomyError_default_instance_;

inline constexpr AutonomyCommand::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : stops_{},
        route_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_{static_cast< ::MissionModule::AutonomyCommand_Action >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AutonomyCommand::AutonomyCommand(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AutonomyCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AutonomyCommandDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AutonomyCommandDefaultTypeInternal() {}
  union {
    AutonomyCommand _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AutonomyCommandDefaultTypeInternal _AutonomyCommand_default_instance_;
}  // namespace MissionModule
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_MissionModule_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_MissionModule_2eproto = nullptr;
const ::uint32_t
    TableStruct_MissionModule_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus_Telemetry, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus_Telemetry, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus_Telemetry, _impl_.speed_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus_Telemetry, _impl_.fuel_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus_Telemetry, _impl_.position_),
        ~0u,
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus, _impl_.telemetry_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus, _impl_.state_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyStatus, _impl_.nextstop_),
        0,
        ~0u,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyCommand, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyCommand, _impl_.stops_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyCommand, _impl_.route_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyCommand, _impl_.action_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyError, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MissionModule::AutonomyError, _impl_.finishedstops_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::Station, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::Station, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MissionModule::Station, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::Station, _impl_.position_),
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::MissionModule::Position, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MissionModule::Position, _impl_.latitude_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::Position, _impl_.longitude_),
        PROTOBUF_FIELD_OFFSET(::MissionModule::Position, _impl_.altitude_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::MissionModule::AutonomyStatus_Telemetry)},
        {14, 25, -1, sizeof(::MissionModule::AutonomyStatus)},
        {28, -1, -1, sizeof(::MissionModule::AutonomyCommand)},
        {39, -1, -1, sizeof(::MissionModule::AutonomyError)},
        {48, 58, -1, sizeof(::MissionModule::Station)},
        {60, -1, -1, sizeof(::MissionModule::Position)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::MissionModule::_AutonomyStatus_Telemetry_default_instance_._instance,
    &::MissionModule::_AutonomyStatus_default_instance_._instance,
    &::MissionModule::_AutonomyCommand_default_instance_._instance,
    &::MissionModule::_AutonomyError_default_instance_._instance,
    &::MissionModule::_Station_default_instance_._instance,
    &::MissionModule::_Position_default_instance_._instance,
};
const char descriptor_table_protodef_MissionModule_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023MissionModule.proto\022\rMissionModule\"\330\002\n"
    "\016AutonomyStatus\022:\n\ttelemetry\030\001 \001(\0132\'.Mis"
    "sionModule.AutonomyStatus.Telemetry\0229\n\005s"
    "tate\030\002 \001(\0162#.MissionModule.AutonomyStatu"
    "s.StateB\005\252\001\002\010\002\022(\n\010nextStop\030\003 \001(\0132\026.Missi"
    "onModule.Station\032a\n\tTelemetry\022\024\n\005speed\030\001"
    " \001(\001B\005\252\001\002\010\002\022\023\n\004fuel\030\002 \001(\001B\005\252\001\002\010\002\022)\n\010posi"
    "tion\030\003 \001(\0132\027.MissionModule.Position\"B\n\005S"
    "tate\022\010\n\004IDLE\020\000\022\t\n\005DRIVE\020\001\022\013\n\007IN_STOP\020\002\022\014"
    "\n\010OBSTACLE\020\003\022\t\n\005ERROR\020\004\"\272\001\n\017AutonomyComm"
    "and\022%\n\005stops\030\001 \003(\0132\026.MissionModule.Stati"
    "on\022\024\n\005route\030\002 \001(\tB\005\252\001\002\010\002\022<\n\006action\030\003 \001(\016"
    "2%.MissionModule.AutonomyCommand.ActionB"
    "\005\252\001\002\010\002\",\n\006Action\022\r\n\tNO_ACTION\020\000\022\010\n\004STOP\020"
    "\001\022\t\n\005START\020\002\">\n\rAutonomyError\022-\n\rfinishe"
    "dStops\030\001 \003(\0132\026.MissionModule.Station\"I\n\007"
    "Station\022\023\n\004name\030\001 \001(\tB\005\252\001\002\010\002\022)\n\010position"
    "\030\002 \001(\0132\027.MissionModule.Position\"V\n\010Posit"
    "ion\022\027\n\010latitude\030\001 \001(\001B\005\252\001\002\010\002\022\030\n\tlongitud"
    "e\030\002 \001(\001B\005\252\001\002\010\002\022\027\n\010altitude\030\003 \001(\001B\005\252\001\002\010\002B"
    ">Z!../internal/pkg/ba_proto;ba_proto\252\002\030G"
    "oogle.Protobuf.ba_protob\010editionsp\350\007"
};
static ::absl::once_flag descriptor_table_MissionModule_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_MissionModule_2eproto = {
    false,
    false,
    876,
    descriptor_table_protodef_MissionModule_2eproto,
    "MissionModule.proto",
    &descriptor_table_MissionModule_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_MissionModule_2eproto::offsets,
    file_level_enum_descriptors_MissionModule_2eproto,
    file_level_service_descriptors_MissionModule_2eproto,
};
namespace MissionModule {
const ::google::protobuf::EnumDescriptor* AutonomyStatus_State_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MissionModule_2eproto);
  return file_level_enum_descriptors_MissionModule_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t AutonomyStatus_State_internal_data_[] = {
    327680u, 0u, };
bool AutonomyStatus_State_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr AutonomyStatus_State AutonomyStatus::IDLE;
constexpr AutonomyStatus_State AutonomyStatus::DRIVE;
constexpr AutonomyStatus_State AutonomyStatus::IN_STOP;
constexpr AutonomyStatus_State AutonomyStatus::OBSTACLE;
constexpr AutonomyStatus_State AutonomyStatus::ERROR;
constexpr AutonomyStatus_State AutonomyStatus::State_MIN;
constexpr AutonomyStatus_State AutonomyStatus::State_MAX;
constexpr int AutonomyStatus::State_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* AutonomyCommand_Action_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MissionModule_2eproto);
  return file_level_enum_descriptors_MissionModule_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t AutonomyCommand_Action_internal_data_[] = {
    196608u, 0u, };
bool AutonomyCommand_Action_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr AutonomyCommand_Action AutonomyCommand::NO_ACTION;
constexpr AutonomyCommand_Action AutonomyCommand::STOP;
constexpr AutonomyCommand_Action AutonomyCommand::START;
constexpr AutonomyCommand_Action AutonomyCommand::Action_MIN;
constexpr AutonomyCommand_Action AutonomyCommand::Action_MAX;
constexpr int AutonomyCommand::Action_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class AutonomyStatus_Telemetry::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AutonomyStatus_Telemetry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_._has_bits_);
};

AutonomyStatus_Telemetry::AutonomyStatus_Telemetry(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MissionModule.AutonomyStatus.Telemetry)
}
inline PROTOBUF_NDEBUG_INLINE AutonomyStatus_Telemetry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MissionModule::AutonomyStatus_Telemetry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

AutonomyStatus_Telemetry::AutonomyStatus_Telemetry(
    ::google::protobuf::Arena* arena,
    const AutonomyStatus_Telemetry& from)
    : ::google::protobuf::Message(arena) {
  AutonomyStatus_Telemetry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::MissionModule::Position>(
                              arena, *from._impl_.position_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, speed_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, speed_),
           offsetof(Impl_, fuel_) -
               offsetof(Impl_, speed_) +
               sizeof(Impl_::fuel_));

  // @@protoc_insertion_point(copy_constructor:MissionModule.AutonomyStatus.Telemetry)
}
inline PROTOBUF_NDEBUG_INLINE AutonomyStatus_Telemetry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AutonomyStatus_Telemetry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, position_),
           0,
           offsetof(Impl_, fuel_) -
               offsetof(Impl_, position_) +
               sizeof(Impl_::fuel_));
}
AutonomyStatus_Telemetry::~AutonomyStatus_Telemetry() {
  // @@protoc_insertion_point(destructor:MissionModule.AutonomyStatus.Telemetry)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AutonomyStatus_Telemetry::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.position_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AutonomyStatus_Telemetry::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_._cached_size_),
              false,
          },
          &AutonomyStatus_Telemetry::MergeImpl,
          &AutonomyStatus_Telemetry::kDescriptorMethods,
          &descriptor_table_MissionModule_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> AutonomyStatus_Telemetry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AutonomyStatus_Telemetry_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MissionModule::AutonomyStatus_Telemetry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double speed = 1 [features = {
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_.speed_)}},
    // double fuel = 2 [features = {
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_.fuel_)}},
    // .MissionModule.Position position = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double speed = 1 [features = {
    {PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_.speed_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double fuel = 2 [features = {
    {PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_.fuel_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // .MissionModule.Position position = 3;
    {PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_.position_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MissionModule::Position>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void AutonomyStatus_Telemetry::Clear() {
// @@protoc_insertion_point(message_clear_start:MissionModule.AutonomyStatus.Telemetry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.position_ != nullptr);
    _impl_.position_->Clear();
  }
  ::memset(&_impl_.speed_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.fuel_) -
      reinterpret_cast<char*>(&_impl_.speed_)) + sizeof(_impl_.fuel_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AutonomyStatus_Telemetry::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MissionModule.AutonomyStatus.Telemetry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double speed = 1 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_speed = this->_internal_speed();
  ::uint64_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_speed(), target);
  }

  // double fuel = 2 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_fuel = this->_internal_fuel();
  ::uint64_t raw_fuel;
  memcpy(&raw_fuel, &tmp_fuel, sizeof(tmp_fuel));
  if (raw_fuel != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_fuel(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .MissionModule.Position position = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.position_, _impl_.position_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MissionModule.AutonomyStatus.Telemetry)
  return target;
}

::size_t AutonomyStatus_Telemetry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MissionModule.AutonomyStatus.Telemetry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // .MissionModule.Position position = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.position_);
  }

  // double speed = 1 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_speed = this->_internal_speed();
  ::uint64_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    total_size += 9;
  }

  // double fuel = 2 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_fuel = this->_internal_fuel();
  ::uint64_t raw_fuel;
  memcpy(&raw_fuel, &tmp_fuel, sizeof(tmp_fuel));
  if (raw_fuel != 0) {
    total_size += 9;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AutonomyStatus_Telemetry::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AutonomyStatus_Telemetry*>(&to_msg);
  auto& from = static_cast<const AutonomyStatus_Telemetry&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:MissionModule.AutonomyStatus.Telemetry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.position_ != nullptr);
    if (_this->_impl_.position_ == nullptr) {
      _this->_impl_.position_ =
          ::google::protobuf::Message::CopyConstruct<::MissionModule::Position>(arena, *from._impl_.position_);
    } else {
      _this->_impl_.position_->MergeFrom(*from._impl_.position_);
    }
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_speed = from._internal_speed();
  ::uint64_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    _this->_impl_.speed_ = from._impl_.speed_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_fuel = from._internal_fuel();
  ::uint64_t raw_fuel;
  memcpy(&raw_fuel, &tmp_fuel, sizeof(tmp_fuel));
  if (raw_fuel != 0) {
    _this->_impl_.fuel_ = from._impl_.fuel_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AutonomyStatus_Telemetry::CopyFrom(const AutonomyStatus_Telemetry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MissionModule.AutonomyStatus.Telemetry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AutonomyStatus_Telemetry::InternalSwap(AutonomyStatus_Telemetry* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_.fuel_)
      + sizeof(AutonomyStatus_Telemetry::_impl_.fuel_)
      - PROTOBUF_FIELD_OFFSET(AutonomyStatus_Telemetry, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::google::protobuf::Metadata AutonomyStatus_Telemetry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AutonomyStatus::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AutonomyStatus>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_._has_bits_);
};

AutonomyStatus::AutonomyStatus(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MissionModule.AutonomyStatus)
}
inline PROTOBUF_NDEBUG_INLINE AutonomyStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MissionModule::AutonomyStatus& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

AutonomyStatus::AutonomyStatus(
    ::google::protobuf::Arena* arena,
    const AutonomyStatus& from)
    : ::google::protobuf::Message(arena) {
  AutonomyStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.telemetry_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::MissionModule::AutonomyStatus_Telemetry>(
                              arena, *from._impl_.telemetry_)
                        : nullptr;
  _impl_.nextstop_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::MissionModule::Station>(
                              arena, *from._impl_.nextstop_)
                        : nullptr;
  _impl_.state_ = from._impl_.state_;

  // @@protoc_insertion_point(copy_constructor:MissionModule.AutonomyStatus)
}
inline PROTOBUF_NDEBUG_INLINE AutonomyStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AutonomyStatus::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, telemetry_),
           0,
           offsetof(Impl_, state_) -
               offsetof(Impl_, telemetry_) +
               sizeof(Impl_::state_));
}
AutonomyStatus::~AutonomyStatus() {
  // @@protoc_insertion_point(destructor:MissionModule.AutonomyStatus)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AutonomyStatus::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.telemetry_;
  delete _impl_.nextstop_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AutonomyStatus::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_._cached_size_),
              false,
          },
          &AutonomyStatus::MergeImpl,
          &AutonomyStatus::kDescriptorMethods,
          &descriptor_table_MissionModule_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> AutonomyStatus::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AutonomyStatus_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MissionModule::AutonomyStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .MissionModule.AutonomyStatus.Telemetry telemetry = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_.telemetry_)}},
    // .MissionModule.AutonomyStatus.State state = 2 [features = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AutonomyStatus, _impl_.state_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_.state_)}},
    // .MissionModule.Station nextStop = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_.nextstop_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MissionModule.AutonomyStatus.Telemetry telemetry = 1;
    {PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_.telemetry_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .MissionModule.AutonomyStatus.State state = 2 [features = {
    {PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_.state_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .MissionModule.Station nextStop = 3;
    {PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_.nextstop_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MissionModule::AutonomyStatus_Telemetry>()},
    {::_pbi::TcParser::GetTable<::MissionModule::Station>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void AutonomyStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:MissionModule.AutonomyStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.telemetry_ != nullptr);
      _impl_.telemetry_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.nextstop_ != nullptr);
      _impl_.nextstop_->Clear();
    }
  }
  _impl_.state_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AutonomyStatus::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MissionModule.AutonomyStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .MissionModule.AutonomyStatus.Telemetry telemetry = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.telemetry_, _impl_.telemetry_->GetCachedSize(), target, stream);
  }

  // .MissionModule.AutonomyStatus.State state = 2 [features = {
  if (this->_internal_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_state(), target);
  }

  // .MissionModule.Station nextStop = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *_impl_.nextstop_, _impl_.nextstop_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MissionModule.AutonomyStatus)
  return target;
}

::size_t AutonomyStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MissionModule.AutonomyStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .MissionModule.AutonomyStatus.Telemetry telemetry = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.telemetry_);
    }

    // .MissionModule.Station nextStop = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.nextstop_);
    }

  }
  // .MissionModule.AutonomyStatus.State state = 2 [features = {
  if (this->_internal_state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AutonomyStatus::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AutonomyStatus*>(&to_msg);
  auto& from = static_cast<const AutonomyStatus&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:MissionModule.AutonomyStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.telemetry_ != nullptr);
      if (_this->_impl_.telemetry_ == nullptr) {
        _this->_impl_.telemetry_ =
            ::google::protobuf::Message::CopyConstruct<::MissionModule::AutonomyStatus_Telemetry>(arena, *from._impl_.telemetry_);
      } else {
        _this->_impl_.telemetry_->MergeFrom(*from._impl_.telemetry_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.nextstop_ != nullptr);
      if (_this->_impl_.nextstop_ == nullptr) {
        _this->_impl_.nextstop_ =
            ::google::protobuf::Message::CopyConstruct<::MissionModule::Station>(arena, *from._impl_.nextstop_);
      } else {
        _this->_impl_.nextstop_->MergeFrom(*from._impl_.nextstop_);
      }
    }
  }
  if (from._internal_state() != 0) {
    _this->_impl_.state_ = from._impl_.state_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AutonomyStatus::CopyFrom(const AutonomyStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MissionModule.AutonomyStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AutonomyStatus::InternalSwap(AutonomyStatus* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_.state_)
      + sizeof(AutonomyStatus::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(AutonomyStatus, _impl_.telemetry_)>(
          reinterpret_cast<char*>(&_impl_.telemetry_),
          reinterpret_cast<char*>(&other->_impl_.telemetry_));
}

::google::protobuf::Metadata AutonomyStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AutonomyCommand::_Internal {
 public:
};

AutonomyCommand::AutonomyCommand(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MissionModule.AutonomyCommand)
}
inline PROTOBUF_NDEBUG_INLINE AutonomyCommand::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MissionModule::AutonomyCommand& from_msg)
      : stops_{visibility, arena, from.stops_},
        route_(arena, from.route_),
        _cached_size_{0} {}

AutonomyCommand::AutonomyCommand(
    ::google::protobuf::Arena* arena,
    const AutonomyCommand& from)
    : ::google::protobuf::Message(arena) {
  AutonomyCommand* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.action_ = from._impl_.action_;

  // @@protoc_insertion_point(copy_constructor:MissionModule.AutonomyCommand)
}
inline PROTOBUF_NDEBUG_INLINE AutonomyCommand::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : stops_{visibility, arena},
        route_(arena),
        _cached_size_{0} {}

inline void AutonomyCommand::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.action_ = {};
}
AutonomyCommand::~AutonomyCommand() {
  // @@protoc_insertion_point(destructor:MissionModule.AutonomyCommand)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AutonomyCommand::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.route_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AutonomyCommand::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AutonomyCommand, _impl_._cached_size_),
              false,
          },
          &AutonomyCommand::MergeImpl,
          &AutonomyCommand::kDescriptorMethods,
          &descriptor_table_MissionModule_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 43, 2> AutonomyCommand::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AutonomyCommand_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MissionModule::AutonomyCommand>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .MissionModule.Station stops = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AutonomyCommand, _impl_.stops_)}},
    // string route = 2 [features = {
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AutonomyCommand, _impl_.route_)}},
    // .MissionModule.AutonomyCommand.Action action = 3 [features = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AutonomyCommand, _impl_.action_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(AutonomyCommand, _impl_.action_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .MissionModule.Station stops = 1;
    {PROTOBUF_FIELD_OFFSET(AutonomyCommand, _impl_.stops_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string route = 2 [features = {
    {PROTOBUF_FIELD_OFFSET(AutonomyCommand, _impl_.route_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .MissionModule.AutonomyCommand.Action action = 3 [features = {
    {PROTOBUF_FIELD_OFFSET(AutonomyCommand, _impl_.action_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MissionModule::Station>()},
  }}, {{
    "\35\0\5\0\0\0\0\0"
    "MissionModule.AutonomyCommand"
    "route"
  }},
};

PROTOBUF_NOINLINE void AutonomyCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:MissionModule.AutonomyCommand)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stops_.Clear();
  _impl_.route_.ClearToEmpty();
  _impl_.action_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AutonomyCommand::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MissionModule.AutonomyCommand)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .MissionModule.Station stops = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_stops_size());
       i < n; i++) {
    const auto& repfield = this->_internal_stops().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // string route = 2 [features = {
  if (!this->_internal_route().empty()) {
    const std::string& _s = this->_internal_route();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MissionModule.AutonomyCommand.route");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // .MissionModule.AutonomyCommand.Action action = 3 [features = {
  if (this->_internal_action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this->_internal_action(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MissionModule.AutonomyCommand)
  return target;
}

::size_t AutonomyCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MissionModule.AutonomyCommand)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .MissionModule.Station stops = 1;
  total_size += 1UL * this->_internal_stops_size();
  for (const auto& msg : this->_internal_stops()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string route = 2 [features = {
  if (!this->_internal_route().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_route());
  }

  // .MissionModule.AutonomyCommand.Action action = 3 [features = {
  if (this->_internal_action() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_action());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AutonomyCommand::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AutonomyCommand*>(&to_msg);
  auto& from = static_cast<const AutonomyCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MissionModule.AutonomyCommand)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_stops()->MergeFrom(
      from._internal_stops());
  if (!from._internal_route().empty()) {
    _this->_internal_set_route(from._internal_route());
  }
  if (from._internal_action() != 0) {
    _this->_impl_.action_ = from._impl_.action_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AutonomyCommand::CopyFrom(const AutonomyCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MissionModule.AutonomyCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AutonomyCommand::InternalSwap(AutonomyCommand* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.stops_.InternalSwap(&other->_impl_.stops_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.route_, &other->_impl_.route_, arena);
  swap(_impl_.action_, other->_impl_.action_);
}

::google::protobuf::Metadata AutonomyCommand::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AutonomyError::_Internal {
 public:
};

AutonomyError::AutonomyError(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MissionModule.AutonomyError)
}
inline PROTOBUF_NDEBUG_INLINE AutonomyError::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MissionModule::AutonomyError& from_msg)
      : finishedstops_{visibility, arena, from.finishedstops_},
        _cached_size_{0} {}

AutonomyError::AutonomyError(
    ::google::protobuf::Arena* arena,
    const AutonomyError& from)
    : ::google::protobuf::Message(arena) {
  AutonomyError* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:MissionModule.AutonomyError)
}
inline PROTOBUF_NDEBUG_INLINE AutonomyError::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : finishedstops_{visibility, arena},
        _cached_size_{0} {}

inline void AutonomyError::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AutonomyError::~AutonomyError() {
  // @@protoc_insertion_point(destructor:MissionModule.AutonomyError)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AutonomyError::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AutonomyError::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AutonomyError, _impl_._cached_size_),
              false,
          },
          &AutonomyError::MergeImpl,
          &AutonomyError::kDescriptorMethods,
          &descriptor_table_MissionModule_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> AutonomyError::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AutonomyError_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MissionModule::AutonomyError>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .MissionModule.Station finishedStops = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AutonomyError, _impl_.finishedstops_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .MissionModule.Station finishedStops = 1;
    {PROTOBUF_FIELD_OFFSET(AutonomyError, _impl_.finishedstops_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MissionModule::Station>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void AutonomyError::Clear() {
// @@protoc_insertion_point(message_clear_start:MissionModule.AutonomyError)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.finishedstops_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AutonomyError::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MissionModule.AutonomyError)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .MissionModule.Station finishedStops = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_finishedstops_size());
       i < n; i++) {
    const auto& repfield = this->_internal_finishedstops().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MissionModule.AutonomyError)
  return target;
}

::size_t AutonomyError::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MissionModule.AutonomyError)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .MissionModule.Station finishedStops = 1;
  total_size += 1UL * this->_internal_finishedstops_size();
  for (const auto& msg : this->_internal_finishedstops()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AutonomyError::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AutonomyError*>(&to_msg);
  auto& from = static_cast<const AutonomyError&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MissionModule.AutonomyError)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_finishedstops()->MergeFrom(
      from._internal_finishedstops());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AutonomyError::CopyFrom(const AutonomyError& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MissionModule.AutonomyError)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AutonomyError::InternalSwap(AutonomyError* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.finishedstops_.InternalSwap(&other->_impl_.finishedstops_);
}

::google::protobuf::Metadata AutonomyError::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Station::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Station>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Station, _impl_._has_bits_);
};

Station::Station(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MissionModule.Station)
}
inline PROTOBUF_NDEBUG_INLINE Station::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MissionModule::Station& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

Station::Station(
    ::google::protobuf::Arena* arena,
    const Station& from)
    : ::google::protobuf::Message(arena) {
  Station* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::MissionModule::Position>(
                              arena, *from._impl_.position_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:MissionModule.Station)
}
inline PROTOBUF_NDEBUG_INLINE Station::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void Station::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.position_ = {};
}
Station::~Station() {
  // @@protoc_insertion_point(destructor:MissionModule.Station)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Station::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  delete _impl_.position_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Station::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Station, _impl_._cached_size_),
              false,
          },
          &Station::MergeImpl,
          &Station::kDescriptorMethods,
          &descriptor_table_MissionModule_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 34, 2> Station::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Station, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Station_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MissionModule::Station>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .MissionModule.Position position = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Station, _impl_.position_)}},
    // string name = 1 [features = {
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Station, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1 [features = {
    {PROTOBUF_FIELD_OFFSET(Station, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .MissionModule.Position position = 2;
    {PROTOBUF_FIELD_OFFSET(Station, _impl_.position_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MissionModule::Position>()},
  }}, {{
    "\25\4\0\0\0\0\0\0"
    "MissionModule.Station"
    "name"
  }},
};

PROTOBUF_NOINLINE void Station::Clear() {
// @@protoc_insertion_point(message_clear_start:MissionModule.Station)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.position_ != nullptr);
    _impl_.position_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Station::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MissionModule.Station)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1 [features = {
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MissionModule.Station.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .MissionModule.Position position = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.position_, _impl_.position_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MissionModule.Station)
  return target;
}

::size_t Station::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MissionModule.Station)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string name = 1 [features = {
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // .MissionModule.Position position = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.position_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Station::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Station*>(&to_msg);
  auto& from = static_cast<const Station&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:MissionModule.Station)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.position_ != nullptr);
    if (_this->_impl_.position_ == nullptr) {
      _this->_impl_.position_ =
          ::google::protobuf::Message::CopyConstruct<::MissionModule::Position>(arena, *from._impl_.position_);
    } else {
      _this->_impl_.position_->MergeFrom(*from._impl_.position_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Station::CopyFrom(const Station& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MissionModule.Station)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Station::InternalSwap(Station* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.position_, other->_impl_.position_);
}

::google::protobuf::Metadata Station::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Position::_Internal {
 public:
};

Position::Position(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MissionModule.Position)
}
Position::Position(
    ::google::protobuf::Arena* arena, const Position& from)
    : Position(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Position::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Position::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, latitude_),
           0,
           offsetof(Impl_, altitude_) -
               offsetof(Impl_, latitude_) +
               sizeof(Impl_::altitude_));
}
Position::~Position() {
  // @@protoc_insertion_point(destructor:MissionModule.Position)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Position::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Position::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Position, _impl_._cached_size_),
              false,
          },
          &Position::MergeImpl,
          &Position::kDescriptorMethods,
          &descriptor_table_MissionModule_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Position::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Position_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MissionModule::Position>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double latitude = 1 [features = {
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(Position, _impl_.latitude_)}},
    // double longitude = 2 [features = {
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Position, _impl_.longitude_)}},
    // double altitude = 3 [features = {
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(Position, _impl_.altitude_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double latitude = 1 [features = {
    {PROTOBUF_FIELD_OFFSET(Position, _impl_.latitude_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double longitude = 2 [features = {
    {PROTOBUF_FIELD_OFFSET(Position, _impl_.longitude_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double altitude = 3 [features = {
    {PROTOBUF_FIELD_OFFSET(Position, _impl_.altitude_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Position::Clear() {
// @@protoc_insertion_point(message_clear_start:MissionModule.Position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.latitude_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.altitude_) -
      reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.altitude_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Position::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MissionModule.Position)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double latitude = 1 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  ::uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_latitude(), target);
  }

  // double longitude = 2 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_longitude = this->_internal_longitude();
  ::uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_longitude(), target);
  }

  // double altitude = 3 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_altitude = this->_internal_altitude();
  ::uint64_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_altitude(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MissionModule.Position)
  return target;
}

::size_t Position::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MissionModule.Position)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // double latitude = 1 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  ::uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    total_size += 9;
  }

  // double longitude = 2 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_longitude = this->_internal_longitude();
  ::uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    total_size += 9;
  }

  // double altitude = 3 [features = {
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_altitude = this->_internal_altitude();
  ::uint64_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    total_size += 9;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Position::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Position*>(&to_msg);
  auto& from = static_cast<const Position&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MissionModule.Position)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_latitude = from._internal_latitude();
  ::uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    _this->_impl_.latitude_ = from._impl_.latitude_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_longitude = from._internal_longitude();
  ::uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    _this->_impl_.longitude_ = from._impl_.longitude_;
  }
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_altitude = from._internal_altitude();
  ::uint64_t raw_altitude;
  memcpy(&raw_altitude, &tmp_altitude, sizeof(tmp_altitude));
  if (raw_altitude != 0) {
    _this->_impl_.altitude_ = from._impl_.altitude_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Position::CopyFrom(const Position& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MissionModule.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Position::InternalSwap(Position* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Position, _impl_.altitude_)
      + sizeof(Position::_impl_.altitude_)
      - PROTOBUF_FIELD_OFFSET(Position, _impl_.latitude_)>(
          reinterpret_cast<char*>(&_impl_.latitude_),
          reinterpret_cast<char*>(&other->_impl_.latitude_));
}

::google::protobuf::Metadata Position::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace MissionModule
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_MissionModule_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
