// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MissionModule.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_MissionModule_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_MissionModule_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_MissionModule_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_MissionModule_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_MissionModule_2eproto;
namespace MissionModule {
class AutonomyCommand;
struct AutonomyCommandDefaultTypeInternal;
extern AutonomyCommandDefaultTypeInternal _AutonomyCommand_default_instance_;
class AutonomyError;
struct AutonomyErrorDefaultTypeInternal;
extern AutonomyErrorDefaultTypeInternal _AutonomyError_default_instance_;
class AutonomyStatus;
struct AutonomyStatusDefaultTypeInternal;
extern AutonomyStatusDefaultTypeInternal _AutonomyStatus_default_instance_;
class AutonomyStatus_Telemetry;
struct AutonomyStatus_TelemetryDefaultTypeInternal;
extern AutonomyStatus_TelemetryDefaultTypeInternal _AutonomyStatus_Telemetry_default_instance_;
class Position;
struct PositionDefaultTypeInternal;
extern PositionDefaultTypeInternal _Position_default_instance_;
class Station;
struct StationDefaultTypeInternal;
extern StationDefaultTypeInternal _Station_default_instance_;
}  // namespace MissionModule
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace MissionModule {
enum AutonomyStatus_State : int {
  AutonomyStatus_State_IDLE = 0,
  AutonomyStatus_State_DRIVE = 1,
  AutonomyStatus_State_IN_STOP = 2,
  AutonomyStatus_State_OBSTACLE = 3,
  AutonomyStatus_State_ERROR = 4,
  AutonomyStatus_State_AutonomyStatus_State_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AutonomyStatus_State_AutonomyStatus_State_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AutonomyStatus_State_IsValid(int value);
extern const uint32_t AutonomyStatus_State_internal_data_[];
constexpr AutonomyStatus_State AutonomyStatus_State_State_MIN = static_cast<AutonomyStatus_State>(0);
constexpr AutonomyStatus_State AutonomyStatus_State_State_MAX = static_cast<AutonomyStatus_State>(4);
constexpr int AutonomyStatus_State_State_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
AutonomyStatus_State_descriptor();
template <typename T>
const std::string& AutonomyStatus_State_Name(T value) {
  static_assert(std::is_same<T, AutonomyStatus_State>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to State_Name().");
  return AutonomyStatus_State_Name(static_cast<AutonomyStatus_State>(value));
}
template <>
inline const std::string& AutonomyStatus_State_Name(AutonomyStatus_State value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AutonomyStatus_State_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool AutonomyStatus_State_Parse(absl::string_view name, AutonomyStatus_State* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AutonomyStatus_State>(
      AutonomyStatus_State_descriptor(), name, value);
}
enum AutonomyCommand_Action : int {
  AutonomyCommand_Action_NO_ACTION = 0,
  AutonomyCommand_Action_STOP = 1,
  AutonomyCommand_Action_START = 2,
  AutonomyCommand_Action_AutonomyCommand_Action_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AutonomyCommand_Action_AutonomyCommand_Action_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AutonomyCommand_Action_IsValid(int value);
extern const uint32_t AutonomyCommand_Action_internal_data_[];
constexpr AutonomyCommand_Action AutonomyCommand_Action_Action_MIN = static_cast<AutonomyCommand_Action>(0);
constexpr AutonomyCommand_Action AutonomyCommand_Action_Action_MAX = static_cast<AutonomyCommand_Action>(2);
constexpr int AutonomyCommand_Action_Action_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
AutonomyCommand_Action_descriptor();
template <typename T>
const std::string& AutonomyCommand_Action_Name(T value) {
  static_assert(std::is_same<T, AutonomyCommand_Action>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Action_Name().");
  return AutonomyCommand_Action_Name(static_cast<AutonomyCommand_Action>(value));
}
template <>
inline const std::string& AutonomyCommand_Action_Name(AutonomyCommand_Action value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AutonomyCommand_Action_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool AutonomyCommand_Action_Parse(absl::string_view name, AutonomyCommand_Action* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AutonomyCommand_Action>(
      AutonomyCommand_Action_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Position final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MissionModule.Position) */ {
 public:
  inline Position() : Position(nullptr) {}
  ~Position() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Position(
      ::google::protobuf::internal::ConstantInitialized);

  inline Position(const Position& from) : Position(nullptr, from) {}
  inline Position(Position&& from) noexcept
      : Position(nullptr, std::move(from)) {}
  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline Position& operator=(Position&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Position& default_instance() {
    return *internal_default_instance();
  }
  static inline const Position* internal_default_instance() {
    return reinterpret_cast<const Position*>(
        &_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(Position& a, Position& b) { a.Swap(&b); }
  inline void Swap(Position* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Position* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Position* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Position>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Position& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Position& from) { Position::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Position* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MissionModule.Position"; }

 protected:
  explicit Position(::google::protobuf::Arena* arena);
  Position(::google::protobuf::Arena* arena, const Position& from);
  Position(::google::protobuf::Arena* arena, Position&& from) noexcept
      : Position(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLatitudeFieldNumber = 1,
    kLongitudeFieldNumber = 2,
    kAltitudeFieldNumber = 3,
  };
  // double latitude = 1 [features = {
  void clear_latitude() ;
  double latitude() const;
  void set_latitude(double value);

  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);

  public:
  // double longitude = 2 [features = {
  void clear_longitude() ;
  double longitude() const;
  void set_longitude(double value);

  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);

  public:
  // double altitude = 3 [features = {
  void clear_altitude() ;
  double altitude() const;
  void set_altitude(double value);

  private:
  double _internal_altitude() const;
  void _internal_set_altitude(double value);

  public:
  // @@protoc_insertion_point(class_scope:MissionModule.Position)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Position_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Position& from_msg);
    double latitude_;
    double longitude_;
    double altitude_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MissionModule_2eproto;
};
// -------------------------------------------------------------------

class Station final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MissionModule.Station) */ {
 public:
  inline Station() : Station(nullptr) {}
  ~Station() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Station(
      ::google::protobuf::internal::ConstantInitialized);

  inline Station(const Station& from) : Station(nullptr, from) {}
  inline Station(Station&& from) noexcept
      : Station(nullptr, std::move(from)) {}
  inline Station& operator=(const Station& from) {
    CopyFrom(from);
    return *this;
  }
  inline Station& operator=(Station&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Station& default_instance() {
    return *internal_default_instance();
  }
  static inline const Station* internal_default_instance() {
    return reinterpret_cast<const Station*>(
        &_Station_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Station& a, Station& b) { a.Swap(&b); }
  inline void Swap(Station* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Station* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Station* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Station>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Station& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Station& from) { Station::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Station* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MissionModule.Station"; }

 protected:
  explicit Station(::google::protobuf::Arena* arena);
  Station(::google::protobuf::Arena* arena, const Station& from);
  Station(::google::protobuf::Arena* arena, Station&& from) noexcept
      : Station(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kPositionFieldNumber = 2,
  };
  // string name = 1 [features = {
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .MissionModule.Position position = 2;
  bool has_position() const;
  void clear_position() ;
  const ::MissionModule::Position& position() const;
  PROTOBUF_NODISCARD ::MissionModule::Position* release_position();
  ::MissionModule::Position* mutable_position();
  void set_allocated_position(::MissionModule::Position* value);
  void unsafe_arena_set_allocated_position(::MissionModule::Position* value);
  ::MissionModule::Position* unsafe_arena_release_position();

  private:
  const ::MissionModule::Position& _internal_position() const;
  ::MissionModule::Position* _internal_mutable_position();

  public:
  // @@protoc_insertion_point(class_scope:MissionModule.Station)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      34, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Station_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Station& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::MissionModule::Position* position_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MissionModule_2eproto;
};
// -------------------------------------------------------------------

class AutonomyStatus_Telemetry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MissionModule.AutonomyStatus.Telemetry) */ {
 public:
  inline AutonomyStatus_Telemetry() : AutonomyStatus_Telemetry(nullptr) {}
  ~AutonomyStatus_Telemetry() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AutonomyStatus_Telemetry(
      ::google::protobuf::internal::ConstantInitialized);

  inline AutonomyStatus_Telemetry(const AutonomyStatus_Telemetry& from) : AutonomyStatus_Telemetry(nullptr, from) {}
  inline AutonomyStatus_Telemetry(AutonomyStatus_Telemetry&& from) noexcept
      : AutonomyStatus_Telemetry(nullptr, std::move(from)) {}
  inline AutonomyStatus_Telemetry& operator=(const AutonomyStatus_Telemetry& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutonomyStatus_Telemetry& operator=(AutonomyStatus_Telemetry&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AutonomyStatus_Telemetry& default_instance() {
    return *internal_default_instance();
  }
  static inline const AutonomyStatus_Telemetry* internal_default_instance() {
    return reinterpret_cast<const AutonomyStatus_Telemetry*>(
        &_AutonomyStatus_Telemetry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AutonomyStatus_Telemetry& a, AutonomyStatus_Telemetry& b) { a.Swap(&b); }
  inline void Swap(AutonomyStatus_Telemetry* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutonomyStatus_Telemetry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AutonomyStatus_Telemetry* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AutonomyStatus_Telemetry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutonomyStatus_Telemetry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutonomyStatus_Telemetry& from) { AutonomyStatus_Telemetry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AutonomyStatus_Telemetry* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MissionModule.AutonomyStatus.Telemetry"; }

 protected:
  explicit AutonomyStatus_Telemetry(::google::protobuf::Arena* arena);
  AutonomyStatus_Telemetry(::google::protobuf::Arena* arena, const AutonomyStatus_Telemetry& from);
  AutonomyStatus_Telemetry(::google::protobuf::Arena* arena, AutonomyStatus_Telemetry&& from) noexcept
      : AutonomyStatus_Telemetry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 3,
    kSpeedFieldNumber = 1,
    kFuelFieldNumber = 2,
  };
  // .MissionModule.Position position = 3;
  bool has_position() const;
  void clear_position() ;
  const ::MissionModule::Position& position() const;
  PROTOBUF_NODISCARD ::MissionModule::Position* release_position();
  ::MissionModule::Position* mutable_position();
  void set_allocated_position(::MissionModule::Position* value);
  void unsafe_arena_set_allocated_position(::MissionModule::Position* value);
  ::MissionModule::Position* unsafe_arena_release_position();

  private:
  const ::MissionModule::Position& _internal_position() const;
  ::MissionModule::Position* _internal_mutable_position();

  public:
  // double speed = 1 [features = {
  void clear_speed() ;
  double speed() const;
  void set_speed(double value);

  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);

  public:
  // double fuel = 2 [features = {
  void clear_fuel() ;
  double fuel() const;
  void set_fuel(double value);

  private:
  double _internal_fuel() const;
  void _internal_set_fuel(double value);

  public:
  // @@protoc_insertion_point(class_scope:MissionModule.AutonomyStatus.Telemetry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AutonomyStatus_Telemetry_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AutonomyStatus_Telemetry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::MissionModule::Position* position_;
    double speed_;
    double fuel_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MissionModule_2eproto;
};
// -------------------------------------------------------------------

class AutonomyStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MissionModule.AutonomyStatus) */ {
 public:
  inline AutonomyStatus() : AutonomyStatus(nullptr) {}
  ~AutonomyStatus() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AutonomyStatus(
      ::google::protobuf::internal::ConstantInitialized);

  inline AutonomyStatus(const AutonomyStatus& from) : AutonomyStatus(nullptr, from) {}
  inline AutonomyStatus(AutonomyStatus&& from) noexcept
      : AutonomyStatus(nullptr, std::move(from)) {}
  inline AutonomyStatus& operator=(const AutonomyStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutonomyStatus& operator=(AutonomyStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AutonomyStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const AutonomyStatus* internal_default_instance() {
    return reinterpret_cast<const AutonomyStatus*>(
        &_AutonomyStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AutonomyStatus& a, AutonomyStatus& b) { a.Swap(&b); }
  inline void Swap(AutonomyStatus* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutonomyStatus* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AutonomyStatus* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AutonomyStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutonomyStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutonomyStatus& from) { AutonomyStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AutonomyStatus* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MissionModule.AutonomyStatus"; }

 protected:
  explicit AutonomyStatus(::google::protobuf::Arena* arena);
  AutonomyStatus(::google::protobuf::Arena* arena, const AutonomyStatus& from);
  AutonomyStatus(::google::protobuf::Arena* arena, AutonomyStatus&& from) noexcept
      : AutonomyStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Telemetry = AutonomyStatus_Telemetry;
  using State = AutonomyStatus_State;
  static constexpr State IDLE = AutonomyStatus_State_IDLE;
  static constexpr State DRIVE = AutonomyStatus_State_DRIVE;
  static constexpr State IN_STOP = AutonomyStatus_State_IN_STOP;
  static constexpr State OBSTACLE = AutonomyStatus_State_OBSTACLE;
  static constexpr State ERROR = AutonomyStatus_State_ERROR;
  static inline bool State_IsValid(int value) {
    return AutonomyStatus_State_IsValid(value);
  }
  static constexpr State State_MIN = AutonomyStatus_State_State_MIN;
  static constexpr State State_MAX = AutonomyStatus_State_State_MAX;
  static constexpr int State_ARRAYSIZE = AutonomyStatus_State_State_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* State_descriptor() {
    return AutonomyStatus_State_descriptor();
  }
  template <typename T>
  static inline const std::string& State_Name(T value) {
    return AutonomyStatus_State_Name(value);
  }
  static inline bool State_Parse(absl::string_view name, State* value) {
    return AutonomyStatus_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kTelemetryFieldNumber = 1,
    kNextStopFieldNumber = 3,
    kStateFieldNumber = 2,
  };
  // .MissionModule.AutonomyStatus.Telemetry telemetry = 1;
  bool has_telemetry() const;
  void clear_telemetry() ;
  const ::MissionModule::AutonomyStatus_Telemetry& telemetry() const;
  PROTOBUF_NODISCARD ::MissionModule::AutonomyStatus_Telemetry* release_telemetry();
  ::MissionModule::AutonomyStatus_Telemetry* mutable_telemetry();
  void set_allocated_telemetry(::MissionModule::AutonomyStatus_Telemetry* value);
  void unsafe_arena_set_allocated_telemetry(::MissionModule::AutonomyStatus_Telemetry* value);
  ::MissionModule::AutonomyStatus_Telemetry* unsafe_arena_release_telemetry();

  private:
  const ::MissionModule::AutonomyStatus_Telemetry& _internal_telemetry() const;
  ::MissionModule::AutonomyStatus_Telemetry* _internal_mutable_telemetry();

  public:
  // .MissionModule.Station nextStop = 3;
  bool has_nextstop() const;
  void clear_nextstop() ;
  const ::MissionModule::Station& nextstop() const;
  PROTOBUF_NODISCARD ::MissionModule::Station* release_nextstop();
  ::MissionModule::Station* mutable_nextstop();
  void set_allocated_nextstop(::MissionModule::Station* value);
  void unsafe_arena_set_allocated_nextstop(::MissionModule::Station* value);
  ::MissionModule::Station* unsafe_arena_release_nextstop();

  private:
  const ::MissionModule::Station& _internal_nextstop() const;
  ::MissionModule::Station* _internal_mutable_nextstop();

  public:
  // .MissionModule.AutonomyStatus.State state = 2 [features = {
  void clear_state() ;
  ::MissionModule::AutonomyStatus_State state() const;
  void set_state(::MissionModule::AutonomyStatus_State value);

  private:
  ::MissionModule::AutonomyStatus_State _internal_state() const;
  void _internal_set_state(::MissionModule::AutonomyStatus_State value);

  public:
  // @@protoc_insertion_point(class_scope:MissionModule.AutonomyStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AutonomyStatus_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AutonomyStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::MissionModule::AutonomyStatus_Telemetry* telemetry_;
    ::MissionModule::Station* nextstop_;
    int state_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MissionModule_2eproto;
};
// -------------------------------------------------------------------

class AutonomyError final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MissionModule.AutonomyError) */ {
 public:
  inline AutonomyError() : AutonomyError(nullptr) {}
  ~AutonomyError() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AutonomyError(
      ::google::protobuf::internal::ConstantInitialized);

  inline AutonomyError(const AutonomyError& from) : AutonomyError(nullptr, from) {}
  inline AutonomyError(AutonomyError&& from) noexcept
      : AutonomyError(nullptr, std::move(from)) {}
  inline AutonomyError& operator=(const AutonomyError& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutonomyError& operator=(AutonomyError&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AutonomyError& default_instance() {
    return *internal_default_instance();
  }
  static inline const AutonomyError* internal_default_instance() {
    return reinterpret_cast<const AutonomyError*>(
        &_AutonomyError_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(AutonomyError& a, AutonomyError& b) { a.Swap(&b); }
  inline void Swap(AutonomyError* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutonomyError* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AutonomyError* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AutonomyError>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutonomyError& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutonomyError& from) { AutonomyError::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AutonomyError* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MissionModule.AutonomyError"; }

 protected:
  explicit AutonomyError(::google::protobuf::Arena* arena);
  AutonomyError(::google::protobuf::Arena* arena, const AutonomyError& from);
  AutonomyError(::google::protobuf::Arena* arena, AutonomyError&& from) noexcept
      : AutonomyError(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFinishedStopsFieldNumber = 1,
  };
  // repeated .MissionModule.Station finishedStops = 1;
  int finishedstops_size() const;
  private:
  int _internal_finishedstops_size() const;

  public:
  void clear_finishedstops() ;
  ::MissionModule::Station* mutable_finishedstops(int index);
  ::google::protobuf::RepeatedPtrField<::MissionModule::Station>* mutable_finishedstops();

  private:
  const ::google::protobuf::RepeatedPtrField<::MissionModule::Station>& _internal_finishedstops() const;
  ::google::protobuf::RepeatedPtrField<::MissionModule::Station>* _internal_mutable_finishedstops();
  public:
  const ::MissionModule::Station& finishedstops(int index) const;
  ::MissionModule::Station* add_finishedstops();
  const ::google::protobuf::RepeatedPtrField<::MissionModule::Station>& finishedstops() const;
  // @@protoc_insertion_point(class_scope:MissionModule.AutonomyError)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AutonomyError_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AutonomyError& from_msg);
    ::google::protobuf::RepeatedPtrField< ::MissionModule::Station > finishedstops_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MissionModule_2eproto;
};
// -------------------------------------------------------------------

class AutonomyCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MissionModule.AutonomyCommand) */ {
 public:
  inline AutonomyCommand() : AutonomyCommand(nullptr) {}
  ~AutonomyCommand() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AutonomyCommand(
      ::google::protobuf::internal::ConstantInitialized);

  inline AutonomyCommand(const AutonomyCommand& from) : AutonomyCommand(nullptr, from) {}
  inline AutonomyCommand(AutonomyCommand&& from) noexcept
      : AutonomyCommand(nullptr, std::move(from)) {}
  inline AutonomyCommand& operator=(const AutonomyCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline AutonomyCommand& operator=(AutonomyCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AutonomyCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const AutonomyCommand* internal_default_instance() {
    return reinterpret_cast<const AutonomyCommand*>(
        &_AutonomyCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(AutonomyCommand& a, AutonomyCommand& b) { a.Swap(&b); }
  inline void Swap(AutonomyCommand* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AutonomyCommand* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AutonomyCommand* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AutonomyCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AutonomyCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AutonomyCommand& from) { AutonomyCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AutonomyCommand* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "MissionModule.AutonomyCommand"; }

 protected:
  explicit AutonomyCommand(::google::protobuf::Arena* arena);
  AutonomyCommand(::google::protobuf::Arena* arena, const AutonomyCommand& from);
  AutonomyCommand(::google::protobuf::Arena* arena, AutonomyCommand&& from) noexcept
      : AutonomyCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Action = AutonomyCommand_Action;
  static constexpr Action NO_ACTION = AutonomyCommand_Action_NO_ACTION;
  static constexpr Action STOP = AutonomyCommand_Action_STOP;
  static constexpr Action START = AutonomyCommand_Action_START;
  static inline bool Action_IsValid(int value) {
    return AutonomyCommand_Action_IsValid(value);
  }
  static constexpr Action Action_MIN = AutonomyCommand_Action_Action_MIN;
  static constexpr Action Action_MAX = AutonomyCommand_Action_Action_MAX;
  static constexpr int Action_ARRAYSIZE = AutonomyCommand_Action_Action_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Action_descriptor() {
    return AutonomyCommand_Action_descriptor();
  }
  template <typename T>
  static inline const std::string& Action_Name(T value) {
    return AutonomyCommand_Action_Name(value);
  }
  static inline bool Action_Parse(absl::string_view name, Action* value) {
    return AutonomyCommand_Action_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kStopsFieldNumber = 1,
    kRouteFieldNumber = 2,
    kActionFieldNumber = 3,
  };
  // repeated .MissionModule.Station stops = 1;
  int stops_size() const;
  private:
  int _internal_stops_size() const;

  public:
  void clear_stops() ;
  ::MissionModule::Station* mutable_stops(int index);
  ::google::protobuf::RepeatedPtrField<::MissionModule::Station>* mutable_stops();

  private:
  const ::google::protobuf::RepeatedPtrField<::MissionModule::Station>& _internal_stops() const;
  ::google::protobuf::RepeatedPtrField<::MissionModule::Station>* _internal_mutable_stops();
  public:
  const ::MissionModule::Station& stops(int index) const;
  ::MissionModule::Station* add_stops();
  const ::google::protobuf::RepeatedPtrField<::MissionModule::Station>& stops() const;
  // string route = 2 [features = {
  void clear_route() ;
  const std::string& route() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_route(Arg_&& arg, Args_... args);
  std::string* mutable_route();
  PROTOBUF_NODISCARD std::string* release_route();
  void set_allocated_route(std::string* value);

  private:
  const std::string& _internal_route() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_route(
      const std::string& value);
  std::string* _internal_mutable_route();

  public:
  // .MissionModule.AutonomyCommand.Action action = 3 [features = {
  void clear_action() ;
  ::MissionModule::AutonomyCommand_Action action() const;
  void set_action(::MissionModule::AutonomyCommand_Action value);

  private:
  ::MissionModule::AutonomyCommand_Action _internal_action() const;
  void _internal_set_action(::MissionModule::AutonomyCommand_Action value);

  public:
  // @@protoc_insertion_point(class_scope:MissionModule.AutonomyCommand)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      43, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AutonomyCommand_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AutonomyCommand& from_msg);
    ::google::protobuf::RepeatedPtrField< ::MissionModule::Station > stops_;
    ::google::protobuf::internal::ArenaStringPtr route_;
    int action_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MissionModule_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AutonomyStatus_Telemetry

// double speed = 1 [features = {
inline void AutonomyStatus_Telemetry::clear_speed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_ = 0;
}
inline double AutonomyStatus_Telemetry::speed() const {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyStatus.Telemetry.speed)
  return _internal_speed();
}
inline void AutonomyStatus_Telemetry::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:MissionModule.AutonomyStatus.Telemetry.speed)
}
inline double AutonomyStatus_Telemetry::_internal_speed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.speed_;
}
inline void AutonomyStatus_Telemetry::_internal_set_speed(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_ = value;
}

// double fuel = 2 [features = {
inline void AutonomyStatus_Telemetry::clear_fuel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fuel_ = 0;
}
inline double AutonomyStatus_Telemetry::fuel() const {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyStatus.Telemetry.fuel)
  return _internal_fuel();
}
inline void AutonomyStatus_Telemetry::set_fuel(double value) {
  _internal_set_fuel(value);
  // @@protoc_insertion_point(field_set:MissionModule.AutonomyStatus.Telemetry.fuel)
}
inline double AutonomyStatus_Telemetry::_internal_fuel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fuel_;
}
inline void AutonomyStatus_Telemetry::_internal_set_fuel(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fuel_ = value;
}

// .MissionModule.Position position = 3;
inline bool AutonomyStatus_Telemetry::has_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline void AutonomyStatus_Telemetry::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ != nullptr) _impl_.position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::MissionModule::Position& AutonomyStatus_Telemetry::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::MissionModule::Position* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::MissionModule::Position&>(::MissionModule::_Position_default_instance_);
}
inline const ::MissionModule::Position& AutonomyStatus_Telemetry::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyStatus.Telemetry.position)
  return _internal_position();
}
inline void AutonomyStatus_Telemetry::unsafe_arena_set_allocated_position(::MissionModule::Position* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::MissionModule::Position*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MissionModule.AutonomyStatus.Telemetry.position)
}
inline ::MissionModule::Position* AutonomyStatus_Telemetry::release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::MissionModule::Position* released = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::MissionModule::Position* AutonomyStatus_Telemetry::unsafe_arena_release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MissionModule.AutonomyStatus.Telemetry.position)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::MissionModule::Position* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::MissionModule::Position* AutonomyStatus_Telemetry::_internal_mutable_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::MissionModule::Position>(GetArena());
    _impl_.position_ = reinterpret_cast<::MissionModule::Position*>(p);
  }
  return _impl_.position_;
}
inline ::MissionModule::Position* AutonomyStatus_Telemetry::mutable_position() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::MissionModule::Position* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:MissionModule.AutonomyStatus.Telemetry.position)
  return _msg;
}
inline void AutonomyStatus_Telemetry::set_allocated_position(::MissionModule::Position* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.position_ = reinterpret_cast<::MissionModule::Position*>(value);
  // @@protoc_insertion_point(field_set_allocated:MissionModule.AutonomyStatus.Telemetry.position)
}

// -------------------------------------------------------------------

// AutonomyStatus

// .MissionModule.AutonomyStatus.Telemetry telemetry = 1;
inline bool AutonomyStatus::has_telemetry() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.telemetry_ != nullptr);
  return value;
}
inline void AutonomyStatus::clear_telemetry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.telemetry_ != nullptr) _impl_.telemetry_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::MissionModule::AutonomyStatus_Telemetry& AutonomyStatus::_internal_telemetry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::MissionModule::AutonomyStatus_Telemetry* p = _impl_.telemetry_;
  return p != nullptr ? *p : reinterpret_cast<const ::MissionModule::AutonomyStatus_Telemetry&>(::MissionModule::_AutonomyStatus_Telemetry_default_instance_);
}
inline const ::MissionModule::AutonomyStatus_Telemetry& AutonomyStatus::telemetry() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyStatus.telemetry)
  return _internal_telemetry();
}
inline void AutonomyStatus::unsafe_arena_set_allocated_telemetry(::MissionModule::AutonomyStatus_Telemetry* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.telemetry_);
  }
  _impl_.telemetry_ = reinterpret_cast<::MissionModule::AutonomyStatus_Telemetry*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MissionModule.AutonomyStatus.telemetry)
}
inline ::MissionModule::AutonomyStatus_Telemetry* AutonomyStatus::release_telemetry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::MissionModule::AutonomyStatus_Telemetry* released = _impl_.telemetry_;
  _impl_.telemetry_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::MissionModule::AutonomyStatus_Telemetry* AutonomyStatus::unsafe_arena_release_telemetry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MissionModule.AutonomyStatus.telemetry)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::MissionModule::AutonomyStatus_Telemetry* temp = _impl_.telemetry_;
  _impl_.telemetry_ = nullptr;
  return temp;
}
inline ::MissionModule::AutonomyStatus_Telemetry* AutonomyStatus::_internal_mutable_telemetry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.telemetry_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::MissionModule::AutonomyStatus_Telemetry>(GetArena());
    _impl_.telemetry_ = reinterpret_cast<::MissionModule::AutonomyStatus_Telemetry*>(p);
  }
  return _impl_.telemetry_;
}
inline ::MissionModule::AutonomyStatus_Telemetry* AutonomyStatus::mutable_telemetry() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::MissionModule::AutonomyStatus_Telemetry* _msg = _internal_mutable_telemetry();
  // @@protoc_insertion_point(field_mutable:MissionModule.AutonomyStatus.telemetry)
  return _msg;
}
inline void AutonomyStatus::set_allocated_telemetry(::MissionModule::AutonomyStatus_Telemetry* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.telemetry_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.telemetry_ = reinterpret_cast<::MissionModule::AutonomyStatus_Telemetry*>(value);
  // @@protoc_insertion_point(field_set_allocated:MissionModule.AutonomyStatus.telemetry)
}

// .MissionModule.AutonomyStatus.State state = 2 [features = {
inline void AutonomyStatus::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0;
}
inline ::MissionModule::AutonomyStatus_State AutonomyStatus::state() const {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyStatus.state)
  return _internal_state();
}
inline void AutonomyStatus::set_state(::MissionModule::AutonomyStatus_State value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:MissionModule.AutonomyStatus.state)
}
inline ::MissionModule::AutonomyStatus_State AutonomyStatus::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::MissionModule::AutonomyStatus_State>(_impl_.state_);
}
inline void AutonomyStatus::_internal_set_state(::MissionModule::AutonomyStatus_State value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// .MissionModule.Station nextStop = 3;
inline bool AutonomyStatus::has_nextstop() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.nextstop_ != nullptr);
  return value;
}
inline void AutonomyStatus::clear_nextstop() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.nextstop_ != nullptr) _impl_.nextstop_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::MissionModule::Station& AutonomyStatus::_internal_nextstop() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::MissionModule::Station* p = _impl_.nextstop_;
  return p != nullptr ? *p : reinterpret_cast<const ::MissionModule::Station&>(::MissionModule::_Station_default_instance_);
}
inline const ::MissionModule::Station& AutonomyStatus::nextstop() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyStatus.nextStop)
  return _internal_nextstop();
}
inline void AutonomyStatus::unsafe_arena_set_allocated_nextstop(::MissionModule::Station* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.nextstop_);
  }
  _impl_.nextstop_ = reinterpret_cast<::MissionModule::Station*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MissionModule.AutonomyStatus.nextStop)
}
inline ::MissionModule::Station* AutonomyStatus::release_nextstop() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::MissionModule::Station* released = _impl_.nextstop_;
  _impl_.nextstop_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::MissionModule::Station* AutonomyStatus::unsafe_arena_release_nextstop() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MissionModule.AutonomyStatus.nextStop)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::MissionModule::Station* temp = _impl_.nextstop_;
  _impl_.nextstop_ = nullptr;
  return temp;
}
inline ::MissionModule::Station* AutonomyStatus::_internal_mutable_nextstop() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.nextstop_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::MissionModule::Station>(GetArena());
    _impl_.nextstop_ = reinterpret_cast<::MissionModule::Station*>(p);
  }
  return _impl_.nextstop_;
}
inline ::MissionModule::Station* AutonomyStatus::mutable_nextstop() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::MissionModule::Station* _msg = _internal_mutable_nextstop();
  // @@protoc_insertion_point(field_mutable:MissionModule.AutonomyStatus.nextStop)
  return _msg;
}
inline void AutonomyStatus::set_allocated_nextstop(::MissionModule::Station* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.nextstop_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.nextstop_ = reinterpret_cast<::MissionModule::Station*>(value);
  // @@protoc_insertion_point(field_set_allocated:MissionModule.AutonomyStatus.nextStop)
}

// -------------------------------------------------------------------

// AutonomyCommand

// repeated .MissionModule.Station stops = 1;
inline int AutonomyCommand::_internal_stops_size() const {
  return _internal_stops().size();
}
inline int AutonomyCommand::stops_size() const {
  return _internal_stops_size();
}
inline void AutonomyCommand::clear_stops() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stops_.Clear();
}
inline ::MissionModule::Station* AutonomyCommand::mutable_stops(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:MissionModule.AutonomyCommand.stops)
  return _internal_mutable_stops()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::MissionModule::Station>* AutonomyCommand::mutable_stops()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:MissionModule.AutonomyCommand.stops)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_stops();
}
inline const ::MissionModule::Station& AutonomyCommand::stops(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyCommand.stops)
  return _internal_stops().Get(index);
}
inline ::MissionModule::Station* AutonomyCommand::add_stops() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::MissionModule::Station* _add = _internal_mutable_stops()->Add();
  // @@protoc_insertion_point(field_add:MissionModule.AutonomyCommand.stops)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::MissionModule::Station>& AutonomyCommand::stops() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:MissionModule.AutonomyCommand.stops)
  return _internal_stops();
}
inline const ::google::protobuf::RepeatedPtrField<::MissionModule::Station>&
AutonomyCommand::_internal_stops() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stops_;
}
inline ::google::protobuf::RepeatedPtrField<::MissionModule::Station>*
AutonomyCommand::_internal_mutable_stops() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.stops_;
}

// string route = 2 [features = {
inline void AutonomyCommand::clear_route() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.route_.ClearToEmpty();
}
inline const std::string& AutonomyCommand::route() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyCommand.route)
  return _internal_route();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AutonomyCommand::set_route(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.route_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MissionModule.AutonomyCommand.route)
}
inline std::string* AutonomyCommand::mutable_route() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_route();
  // @@protoc_insertion_point(field_mutable:MissionModule.AutonomyCommand.route)
  return _s;
}
inline const std::string& AutonomyCommand::_internal_route() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.route_.Get();
}
inline void AutonomyCommand::_internal_set_route(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.route_.Set(value, GetArena());
}
inline std::string* AutonomyCommand::_internal_mutable_route() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.route_.Mutable( GetArena());
}
inline std::string* AutonomyCommand::release_route() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MissionModule.AutonomyCommand.route)
  return _impl_.route_.Release();
}
inline void AutonomyCommand::set_allocated_route(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.route_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.route_.IsDefault()) {
          _impl_.route_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MissionModule.AutonomyCommand.route)
}

// .MissionModule.AutonomyCommand.Action action = 3 [features = {
inline void AutonomyCommand::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = 0;
}
inline ::MissionModule::AutonomyCommand_Action AutonomyCommand::action() const {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyCommand.action)
  return _internal_action();
}
inline void AutonomyCommand::set_action(::MissionModule::AutonomyCommand_Action value) {
  _internal_set_action(value);
  // @@protoc_insertion_point(field_set:MissionModule.AutonomyCommand.action)
}
inline ::MissionModule::AutonomyCommand_Action AutonomyCommand::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::MissionModule::AutonomyCommand_Action>(_impl_.action_);
}
inline void AutonomyCommand::_internal_set_action(::MissionModule::AutonomyCommand_Action value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = value;
}

// -------------------------------------------------------------------

// AutonomyError

// repeated .MissionModule.Station finishedStops = 1;
inline int AutonomyError::_internal_finishedstops_size() const {
  return _internal_finishedstops().size();
}
inline int AutonomyError::finishedstops_size() const {
  return _internal_finishedstops_size();
}
inline void AutonomyError::clear_finishedstops() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.finishedstops_.Clear();
}
inline ::MissionModule::Station* AutonomyError::mutable_finishedstops(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:MissionModule.AutonomyError.finishedStops)
  return _internal_mutable_finishedstops()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::MissionModule::Station>* AutonomyError::mutable_finishedstops()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:MissionModule.AutonomyError.finishedStops)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_finishedstops();
}
inline const ::MissionModule::Station& AutonomyError::finishedstops(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MissionModule.AutonomyError.finishedStops)
  return _internal_finishedstops().Get(index);
}
inline ::MissionModule::Station* AutonomyError::add_finishedstops() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::MissionModule::Station* _add = _internal_mutable_finishedstops()->Add();
  // @@protoc_insertion_point(field_add:MissionModule.AutonomyError.finishedStops)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::MissionModule::Station>& AutonomyError::finishedstops() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:MissionModule.AutonomyError.finishedStops)
  return _internal_finishedstops();
}
inline const ::google::protobuf::RepeatedPtrField<::MissionModule::Station>&
AutonomyError::_internal_finishedstops() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.finishedstops_;
}
inline ::google::protobuf::RepeatedPtrField<::MissionModule::Station>*
AutonomyError::_internal_mutable_finishedstops() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.finishedstops_;
}

// -------------------------------------------------------------------

// Station

// string name = 1 [features = {
inline void Station::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Station::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MissionModule.Station.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Station::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MissionModule.Station.name)
}
inline std::string* Station::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:MissionModule.Station.name)
  return _s;
}
inline const std::string& Station::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Station::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* Station::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* Station::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MissionModule.Station.name)
  return _impl_.name_.Release();
}
inline void Station::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MissionModule.Station.name)
}

// .MissionModule.Position position = 2;
inline bool Station::has_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline void Station::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ != nullptr) _impl_.position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::MissionModule::Position& Station::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::MissionModule::Position* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::MissionModule::Position&>(::MissionModule::_Position_default_instance_);
}
inline const ::MissionModule::Position& Station::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MissionModule.Station.position)
  return _internal_position();
}
inline void Station::unsafe_arena_set_allocated_position(::MissionModule::Position* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::MissionModule::Position*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MissionModule.Station.position)
}
inline ::MissionModule::Position* Station::release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::MissionModule::Position* released = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::MissionModule::Position* Station::unsafe_arena_release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MissionModule.Station.position)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::MissionModule::Position* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::MissionModule::Position* Station::_internal_mutable_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::MissionModule::Position>(GetArena());
    _impl_.position_ = reinterpret_cast<::MissionModule::Position*>(p);
  }
  return _impl_.position_;
}
inline ::MissionModule::Position* Station::mutable_position() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::MissionModule::Position* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:MissionModule.Station.position)
  return _msg;
}
inline void Station::set_allocated_position(::MissionModule::Position* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.position_ = reinterpret_cast<::MissionModule::Position*>(value);
  // @@protoc_insertion_point(field_set_allocated:MissionModule.Station.position)
}

// -------------------------------------------------------------------

// Position

// double latitude = 1 [features = {
inline void Position::clear_latitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_ = 0;
}
inline double Position::latitude() const {
  // @@protoc_insertion_point(field_get:MissionModule.Position.latitude)
  return _internal_latitude();
}
inline void Position::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:MissionModule.Position.latitude)
}
inline double Position::_internal_latitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.latitude_;
}
inline void Position::_internal_set_latitude(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_ = value;
}

// double longitude = 2 [features = {
inline void Position::clear_longitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_ = 0;
}
inline double Position::longitude() const {
  // @@protoc_insertion_point(field_get:MissionModule.Position.longitude)
  return _internal_longitude();
}
inline void Position::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:MissionModule.Position.longitude)
}
inline double Position::_internal_longitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.longitude_;
}
inline void Position::_internal_set_longitude(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_ = value;
}

// double altitude = 3 [features = {
inline void Position::clear_altitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_ = 0;
}
inline double Position::altitude() const {
  // @@protoc_insertion_point(field_get:MissionModule.Position.altitude)
  return _internal_altitude();
}
inline void Position::set_altitude(double value) {
  _internal_set_altitude(value);
  // @@protoc_insertion_point(field_set:MissionModule.Position.altitude)
}
inline double Position::_internal_altitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.altitude_;
}
inline void Position::_internal_set_altitude(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace MissionModule


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::MissionModule::AutonomyStatus_State> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::MissionModule::AutonomyStatus_State>() {
  return ::MissionModule::AutonomyStatus_State_descriptor();
}
template <>
struct is_proto_enum<::MissionModule::AutonomyCommand_Action> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::MissionModule::AutonomyCommand_Action>() {
  return ::MissionModule::AutonomyCommand_Action_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_MissionModule_2eproto_2epb_2eh
